# Generated by Django 6.0.6 on 2026-07-02 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='Education.educationlevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
