# Generated by Django 6.0.6 on 2026-07-02 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_degree_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree', to='Education.stream'),
        ),
    ]
