# Generated by Django 6.0.4 on 2026-04-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('coursera_link', models.URLField(blank=True, max_length=500)),
                ('youtube_link', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_roles', models.CharField(default='Various Roles', max_length=255)),
                ('average_salary', models.CharField(default='Varies', max_length=100)),
                ('career_growth', models.CharField(default='High', max_length=100)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='career.degree')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='streams',
            field=models.ManyToManyField(blank=True, related_name='degrees', to='career.stream'),
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='career.domain')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('domain', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='DomainSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='career.domain')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_requirements', to='career.skill')),
            ],
            options={
                'unique_together': {('domain', 'skill')},
            },
        ),
    ]
